// reportGenerator.js — assembles and downloads the therapy report PDF using jsPDF + autotable
// All generation is client-side. No data leaves the browser.

import jsPDF from "jspdf";
import "jspdf-autotable";
import { format } from "date-fns";

const PRIMARY = [59, 130, 246]; // blue-500
const MUTED = [100, 116, 139]; // slate-500
const LIGHT_BG = [241, 245, 249]; // slate-100
const FLAG_BG = [254, 243, 199]; // amber-100
const FLAG_TEXT = [146, 64, 14]; // amber-800
const PAGE_W = 210;
const MARGIN = 18;
const CONTENT_W = PAGE_W - MARGIN * 2;

function rgb(arr) { return { r: arr[0], g: arr[1], b: arr[2] }; }

function pageFooter(doc, config, pageNum) {
  const totalPages = doc.internal.getNumberOfPages();
  const y = doc.internal.pageSize.height - 8;
  doc.setFontSize(7);
  doc.setTextColor(...MUTED);
  doc.text(config.systemName || "Therapy Report", MARGIN, y);
  doc.text(`${config.dateFrom} to ${config.dateTo}`, PAGE_W / 2, y, { align: "center" });
  doc.text(`Page ${pageNum} of ${totalPages}`, PAGE_W - MARGIN, y, { align: "right" });
  if (config.confidentialityNotice) {
    doc.setFontSize(6);
    doc.text("Personal health information — shared voluntarily for therapeutic purposes.", PAGE_W / 2, y + 4, { align: "center" });
  }
}

function sectionHeader(doc, title, y) {
  doc.setFillColor(...PRIMARY);
  doc.rect(MARGIN, y, CONTENT_W, 7, "F");
  doc.setFontSize(10);
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.text(title, MARGIN + 3, y + 5);
  doc.setFont("helvetica", "normal");
  return y + 12;
}

function checkPageBreak(doc, y, needed = 20) {
  if (y + needed > doc.internal.pageSize.height - 18) {
    doc.addPage();
    return 18;
  }
  return y;
}

function wrappedText(doc, text, x, y, maxWidth, lineHeight = 5) {
  const lines = doc.splitTextToSize(text, maxWidth);
  lines.forEach(line => {
    doc.text(line, x, y);
    y += lineHeight;
  });
  return y;
}

function flagBadge(doc, label, x, y) {
  const w = doc.getTextWidth(label) + 4;
  doc.setFillColor(...FLAG_BG);
  doc.roundedRect(x, y - 3.5, w, 5, 1, 1, "F");
  doc.setTextColor(...FLAG_TEXT);
  doc.setFontSize(7);
  doc.text(label, x + 2, y);
  doc.setTextColor(30, 30, 30);
  doc.setFontSize(9);
  return x + w + 3;
}

// ── COVER PAGE ────────────────────────────────────────────────────────────────

function addCoverPage(doc, config) {
  const cy = 60;
  doc.setFillColor(...PRIMARY);
  doc.rect(0, 0, PAGE_W, 4, "F");

  doc.setFontSize(22);
  doc.setTextColor(30, 30, 30);
  doc.setFont("helvetica", "bold");
  doc.text(config.systemName || "My System", PAGE_W / 2, cy, { align: "center" });

  doc.setFontSize(14);
  doc.setTextColor(...MUTED);
  doc.setFont("helvetica", "normal");
  doc.text("Therapy Report", PAGE_W / 2, cy + 10, { align: "center" });

  doc.setFontSize(10);
  doc.text(`${config.dateFrom} – ${config.dateTo}`, PAGE_W / 2, cy + 20, { align: "center" });

  // Divider
  doc.setDrawColor(...PRIMARY);
  doc.setLineWidth(0.5);
  doc.line(MARGIN + 20, cy + 26, PAGE_W - MARGIN - 20, cy + 26);

  let ty = cy + 36;
  if (config.therapistName) {
    doc.setFontSize(10);
    doc.setTextColor(30, 30, 30);
    doc.text(`Prepared for: ${config.therapistName}`, PAGE_W / 2, ty, { align: "center" });
    ty += 7;
  }
  if (config.sessionDate) {
    doc.text(`Session date: ${config.sessionDate}`, PAGE_W / 2, ty, { align: "center" });
    ty += 7;
  }

  if (config.coverNote) {
    ty += 6;
    doc.setFontSize(9);
    doc.setTextColor(...MUTED);
    const noteLines = doc.splitTextToSize(config.coverNote, CONTENT_W - 20);
    doc.setFillColor(...LIGHT_BG);
    const boxH = noteLines.length * 5 + 10;
    doc.roundedRect(MARGIN + 10, ty - 5, CONTENT_W - 20, boxH, 2, 2, "F");
    doc.setTextColor(50, 50, 50);
    noteLines.forEach(line => { doc.text(line, PAGE_W / 2, ty, { align: "center" }); ty += 5; });
  }

  // Footer
  const fy = doc.internal.pageSize.height - 18;
  doc.setFontSize(8);
  doc.setTextColor(...MUTED);
  doc.text(`Generated by Oceans Symphony · ${format(new Date(), "MMMM d, yyyy")}`, PAGE_W / 2, fy, { align: "center" });
  if (config.confidentialityNotice) {
    doc.setFontSize(6.5);
    doc.text("Personal health information — shared voluntarily for therapeutic purposes.", PAGE_W / 2, fy + 5, { align: "center" });
  }
}

// ── OVERVIEW ──────────────────────────────────────────────────────────────────

function addOverview(doc, overview, y) {
  y = sectionHeader(doc, "At a Glance", y);
  doc.setFontSize(9);
  doc.setTextColor(50, 50, 50);

  const items = [
    [`${overview.frontingCount}`, "fronting sessions recorded"],
    [`${overview.checkInCount}`, "emotion check-ins"],
    [`${overview.journalCount}`, "journal entries"],
    [`${overview.diaryCardCount}`, "diary cards"],
    [`${overview.alterCount}`, "system members"],
  ];

  items.forEach(([n, label]) => {
    y = checkPageBreak(doc, y, 7);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...PRIMARY);
    doc.text(`${n}`, MARGIN + 3, y);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(50, 50, 50);
    doc.text(label, MARGIN + 3 + doc.getTextWidth(n) + 2, y);
    y += 6;
  });

  return y + 4;
}

// ── FRONTING HISTORY ──────────────────────────────────────────────────────────

function addFrontingSection(doc, frontingData, y) {
  y = checkPageBreak(doc, y, 30);
  y = sectionHeader(doc, "Fronting History", y);

  if (frontingData.summaryTable.length > 0) {
    doc.autoTable({
      startY: y,
      head: [["System Member", "Total Time", "Sessions", "Primary"]],
      body: frontingData.summaryTable.map(r => [r.name, r.total, r.sessions, r.primary]),
      margin: { left: MARGIN, right: MARGIN },
      styles: { fontSize: 8, cellPadding: 2.5 },
      headStyles: { fillColor: PRIMARY, textColor: [255, 255, 255], fontSize: 8 },
      alternateRowStyles: { fillColor: LIGHT_BG },
      tableWidth: CONTENT_W,
    });
    y = doc.lastAutoTable.finalY + 6;
  }

  if (frontingData.noteworthy.length > 0) {
    y = checkPageBreak(doc, y, 14);
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(30, 30, 30);
    doc.text("Notable events", MARGIN, y);
    doc.setFont("helvetica", "normal");
    y += 5;
    frontingData.noteworthy.forEach(ev => {
      y = checkPageBreak(doc, y, 8);
      doc.setFontSize(8);
      doc.setTextColor(...MUTED);
      doc.text(ev.date || "", MARGIN + 2, y);
      flagBadge(doc, ev.label, MARGIN + 50, y);
      if (ev.detail) { doc.setTextColor(80, 80, 80); doc.text(ev.detail, MARGIN + 2, y + 5); y += 5; }
      y += 6;
    });
  }

  return y + 4;
}

// ── EMOTION CHECK-INS ─────────────────────────────────────────────────────────

function addEmotionSection(doc, emotionData, y) {
  y = checkPageBreak(doc, y, 30);
  y = sectionHeader(doc, "Emotion Check-Ins", y);

  if (emotionData.topEmotions.length > 0) {
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(30, 30, 30);
    doc.text("Most frequent emotions:", MARGIN, y);
    doc.setFont("helvetica", "normal");
    y += 5;
    emotionData.topEmotions.slice(0, 6).forEach(e => {
      y = checkPageBreak(doc, y, 6);
      doc.setFontSize(8);
      doc.setTextColor(50, 50, 50);
      doc.text(`• ${e.emotion} (${e.count}×)`, MARGIN + 3, y);
      y += 5;
    });
    y += 3;
  }

  if (emotionData.noteworthy.length > 0) {
    y = checkPageBreak(doc, y, 12);
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(30, 30, 30);
    doc.text("Notable check-ins:", MARGIN, y);
    doc.setFont("helvetica", "normal");
    y += 5;
    emotionData.noteworthy.forEach(ev => {
      y = checkPageBreak(doc, y, 12);
      doc.setFontSize(8);
      doc.setTextColor(...MUTED);
      doc.text(ev.date, MARGIN + 2, y);
      flagBadge(doc, ev.label, MARGIN + 55, y);
      y += 5;
      doc.setTextColor(60, 60, 60);
      if (ev.emotions) doc.text(`Emotions: ${ev.emotions}`, MARGIN + 4, y);
      y += 5;
    });
  }

  return y + 4;
}

// ── SYMPTOMS ──────────────────────────────────────────────────────────────────

function addSymptomsSection(doc, symptomsData, y) {
  y = checkPageBreak(doc, y, 30);
  y = sectionHeader(doc, "Symptoms & Habits", y);

  if (symptomsData.summaryTable.length > 0) {
    doc.autoTable({
      startY: y,
      head: [["Symptom / Habit", "Check-ins", "Avg Severity", "Sessions", "Total Duration"]],
      body: symptomsData.summaryTable.map(r => [r.label, r.count, r.avgSeverity, r.activeSessions, r.totalDuration]),
      margin: { left: MARGIN, right: MARGIN },
      styles: { fontSize: 8, cellPadding: 2.5 },
      headStyles: { fillColor: PRIMARY, textColor: [255, 255, 255], fontSize: 8 },
      alternateRowStyles: { fillColor: LIGHT_BG },
      tableWidth: CONTENT_W,
    });
    y = doc.lastAutoTable.finalY + 6;
  }

  if (symptomsData.noteworthy.length > 0) {
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(30, 30, 30);
    doc.text("Notable symptom events:", MARGIN, y);
    doc.setFont("helvetica", "normal");
    y += 5;
    symptomsData.noteworthy.forEach(ev => {
      y = checkPageBreak(doc, y, 8);
      doc.setFontSize(8);
      doc.setTextColor(...MUTED);
      doc.text(ev.date, MARGIN + 2, y);
      doc.setTextColor(60, 60, 60);
      doc.text(ev.label, MARGIN + 55, y);
      flagBadge(doc, ev.flag, MARGIN + 90, y);
      y += 6;
    });
  }

  return y + 4;
}

// ── ACTIVITIES ────────────────────────────────────────────────────────────────

function addActivitiesSection(doc, activitiesData, y) {
  y = checkPageBreak(doc, y, 20);
  y = sectionHeader(doc, "Activities", y);
  if (activitiesData.list.length === 0) {
    doc.setFontSize(8); doc.setTextColor(...MUTED);
    doc.text("No activities recorded in this period.", MARGIN, y); return y + 10;
  }
  doc.autoTable({
    startY: y,
    head: [["Activity", "Times logged", "Total duration"]],
    body: activitiesData.list.slice(0, 15).map(r => [r.name, r.count, r.duration]),
    margin: { left: MARGIN, right: MARGIN },
    styles: { fontSize: 8, cellPadding: 2.5 },
    headStyles: { fillColor: PRIMARY, textColor: [255, 255, 255], fontSize: 8 },
    alternateRowStyles: { fillColor: LIGHT_BG },
    tableWidth: CONTENT_W,
  });
  return doc.lastAutoTable.finalY + 8;
}

// ── JOURNALS ──────────────────────────────────────────────────────────────────

function addJournalsSection(doc, journalData, journalDetail, y) {
  y = checkPageBreak(doc, y, 20);
  y = sectionHeader(doc, "Journal Entries", y);
  if (journalData.length === 0) {
    doc.setFontSize(8); doc.setTextColor(...MUTED);
    doc.text("No journal entries in this period.", MARGIN, y); return y + 10;
  }
  journalData.forEach(j => {
    y = checkPageBreak(doc, y, 14);
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(30, 30, 30);
    doc.text(j.title || "Untitled", MARGIN + 2, y);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(...MUTED);
    doc.text(j.date || "", PAGE_W - MARGIN, y, { align: "right" });
    y += 5;
    if (journalDetail !== "summaries" && (j.excerpt || j.content)) {
      const text = (j.content || j.excerpt || "").slice(0, journalDetail === "excerpts" ? 400 : undefined);
      doc.setTextColor(60, 60, 60);
      doc.setFontSize(8);
      y = wrappedText(doc, text + (journalDetail === "excerpts" && text.length >= 400 ? "…" : ""), MARGIN + 3, y, CONTENT_W - 6, 4.5);
      if (journalDetail === "excerpts") {
        doc.setTextColor(...MUTED);
        doc.setFontSize(7);
        doc.text("Full entry available in app.", MARGIN + 3, y); y += 4;
      }
    }
    y += 5;
  });
  return y + 2;
}

// ── DIARY CARDS ───────────────────────────────────────────────────────────────

function addDiarySection(doc, diaryData, y) {
  y = checkPageBreak(doc, y, 20);
  y = sectionHeader(doc, "Diary Card Log", y);
  if (diaryData.length === 0) {
    doc.setFontSize(8); doc.setTextColor(...MUTED);
    doc.text("No diary cards in this period.", MARGIN, y); return y + 10;
  }
  doc.autoTable({
    startY: y,
    head: [["Date", "Emotions", "Urges", "Body / Mind", "Flags"]],
    body: diaryData.map(d => [d.date, d.emotions, d.urges, d.bodyMind, d.flags.join(", ") || "—"]),
    margin: { left: MARGIN, right: MARGIN },
    styles: { fontSize: 7.5, cellPadding: 2, overflow: "linebreak" },
    headStyles: { fillColor: PRIMARY, textColor: [255, 255, 255], fontSize: 8 },
    alternateRowStyles: { fillColor: LIGHT_BG },
    columnStyles: { 0: { cellWidth: 22 }, 4: { cellWidth: 28 } },
    tableWidth: CONTENT_W,
  });
  return doc.lastAutoTable.finalY + 8;
}

// ── PATTERNS SUMMARY ──────────────────────────────────────────────────────────

function addPatternsSection(doc, summary, y) {
  y = checkPageBreak(doc, y, 30);
  y = sectionHeader(doc, "Patterns Summary", y);
  doc.setFontSize(9);
  doc.setTextColor(50, 50, 50);
  y = wrappedText(doc, summary, MARGIN + 2, y, CONTENT_W - 4, 5.5);
  return y + 8;
}

// ── ALTER APPENDIX ────────────────────────────────────────────────────────────

function addAlterAppendix(doc, appendix, y) {
  if (appendix.length === 0) return y;
  doc.addPage();
  y = 18;
  y = sectionHeader(doc, "Appendix: System Members", y);
  appendix.forEach(a => {
    y = checkPageBreak(doc, y, 18);
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(30, 30, 30);
    doc.text(a.name, MARGIN + 2, y);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(...MUTED);
    const meta = [a.pronouns, a.role].filter(Boolean).join(" · ");
    if (meta) { doc.text(meta, MARGIN + 2, y + 5); y += 5; }
    y += 5;
    if (a.bio) {
      doc.setTextColor(60, 60, 60);
      y = wrappedText(doc, a.bio, MARGIN + 4, y, CONTENT_W - 8, 4.5);
    }
    y += 6;
  });
  return y;
}

// ── MAIN EXPORT ───────────────────────────────────────────────────────────────

export async function generateTherapyReport({
  config,       // { systemName, dateFrom, dateTo, therapistName, sessionDate, coverNote, showCoverPage, confidentialityNotice, journalDetail }
  sections,     // object with keys: overview, fronting, emotions, symptoms, activities, journals, diary, patterns, alterAppendix
  enabledSections, // Set of section keys to include
}) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });

  // Cover page
  if (config.showCoverPage) {
    addCoverPage(doc, config);
    doc.addPage();
  }

  let y = 18;

  if (enabledSections.has("overview")) {
    y = addOverview(doc, sections.overview, y);
  }
  if (enabledSections.has("fronting") && sections.fronting) {
    y = addFrontingSection(doc, sections.fronting, y);
  }
  if (enabledSections.has("emotions") && sections.emotions) {
    y = addEmotionSection(doc, sections.emotions, y);
  }
  if (enabledSections.has("symptoms") && sections.symptoms) {
    y = addSymptomsSection(doc, sections.symptoms, y);
  }
  if (enabledSections.has("activities") && sections.activities) {
    y = addActivitiesSection(doc, sections.activities, y);
  }
  if (enabledSections.has("journals") && sections.journals) {
    y = addJournalsSection(doc, sections.journals, config.journalDetail || "summaries", y);
  }
  if (enabledSections.has("diary") && sections.diary) {
    y = addDiarySection(doc, sections.diary, y);
  }
  if (enabledSections.has("patterns") && sections.patterns) {
    y = addPatternsSection(doc, sections.patterns, y);
  }
  if (enabledSections.has("alterAppendix") && sections.alterAppendix?.length > 0) {
    addAlterAppendix(doc, sections.alterAppendix, y);
  }

  // Add footers to all pages
  const total = doc.internal.getNumberOfPages();
  for (let i = 1; i <= total; i++) {
    doc.setPage(i);
    pageFooter(doc, config, i);
  }

  // Download
  const slug = (config.systemName || "system").toLowerCase().replace(/\s+/g, "-").replace(/[^a-z0-9-]/g, "");
  const filename = `${slug}-therapy-report-${config.dateFrom}-to-${config.dateTo}.pdf`;
  doc.save(filename);
}