// reportGenerator.js — assembles and downloads therapy report PDF using jsPDF
// All generation is client-side. No data leaves the browser.

import jsPDF from "jspdf";
import { format } from "date-fns";

const PRIMARY = [59, 130, 246];
const MUTED = [100, 116, 139];
const LIGHT_BG = [241, 245, 249];
const FLAG_BG = [254, 243, 199];
const FLAG_TEXT = [146, 64, 14];
const PAGE_W = 210;
const MARGIN = 18;
const CONTENT_W = PAGE_W - MARGIN * 2;

function pageFooter(doc, config, pageNum) {
  const totalPages = doc.internal.getNumberOfPages();
  const y = doc.internal.pageSize.height - 8;
  doc.setFontSize(7);
  doc.setTextColor(...MUTED);
  doc.text(config.systemName || "Therapy Report", MARGIN, y);
  doc.text(`${config.dateFrom} to ${config.dateTo}`, PAGE_W / 2, y, { align: "center" });
  doc.text(`Page ${pageNum} of ${totalPages}`, PAGE_W - MARGIN, y, { align: "right" });
  if (config.confidentialityNotice) {
    doc.setFontSize(6);
    doc.text("Personal health information — shared voluntarily for therapeutic purposes.", PAGE_W / 2, y + 4, { align: "center" });
  }
}

function sectionHeader(doc, title, y) {
  doc.setFillColor(...PRIMARY);
  doc.rect(MARGIN, y, CONTENT_W, 7, "F");
  doc.setFontSize(10);
  doc.setTextColor(255, 255, 255);
  doc.setFont("helvetica", "bold");
  doc.text(title, MARGIN + 3, y + 5);
  doc.setFont("helvetica", "normal");
  return y + 12;
}

function checkPageBreak(doc, y, needed = 20) {
  if (y + needed > doc.internal.pageSize.height - 18) {
    doc.addPage();
    return 18;
  }
  return y;
}

function wrappedText(doc, text, x, y, maxWidth, lineHeight = 5) {
  const lines = doc.splitTextToSize(text, maxWidth);
  lines.forEach(line => {
    doc.text(line, x, y);
    y += lineHeight;
  });
  return y;
}

function flagBadge(doc, label, x, y) {
  const w = doc.getTextWidth(label) + 4;
  doc.setFillColor(...FLAG_BG);
  doc.roundedRect(x, y - 3.5, w, 5, 1, 1, "F");
  doc.setTextColor(...FLAG_TEXT);
  doc.setFontSize(7);
  doc.text(label, x + 2, y);
  doc.setTextColor(30, 30, 30);
  doc.setFontSize(9);
  return x + w + 3;
}

function drawTable(doc, headers, rows, y, colWidths = null) {
  const colW = colWidths || headers.map(() => CONTENT_W / headers.length);
  const rowH = 6;
  
  // Header
  doc.setFillColor(...PRIMARY);
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(8);
  doc.setFont("helvetica", "bold");
  let x = MARGIN;
  headers.forEach((h, i) => {
    doc.rect(x, y, colW[i], rowH, "F");
    doc.text(h, x + 1.5, y + 4.5);
    x += colW[i];
  });
  y += rowH;

  // Rows
  doc.setTextColor(50, 50, 50);
  doc.setFont("helvetica", "normal");
  rows.forEach((row, ri) => {
    if (ri % 2 === 1) {
      x = MARGIN;
      doc.setFillColor(...LIGHT_BG);
      headers.forEach((_, i) => { doc.rect(x, y, colW[i], rowH, "F"); x += colW[i]; });
    }
    x = MARGIN;
    row.forEach((cell, i) => {
      const text = String(cell || "");
      const truncated = text.length > 20 ? text.slice(0, 17) + "…" : text;
      doc.text(truncated, x + 1, y + 4.5);
      x += colW[i];
    });
    y += rowH;
  });
  
  return y + 2;
}

// ── COVER PAGE ────────────────────────────────────────────────────────────────

function addCoverPage(doc, config) {
  const cy = 60;
  doc.setFillColor(...PRIMARY);
  doc.rect(0, 0, PAGE_W, 4, "F");

  doc.setFontSize(22);
  doc.setTextColor(30, 30, 30);
  doc.setFont("helvetica", "bold");
  doc.text(config.systemName || "My System", PAGE_W / 2, cy, { align: "center" });

  doc.setFontSize(14);
  doc.setTextColor(...MUTED);
  doc.setFont("helvetica", "normal");
  doc.text("Therapy Report", PAGE_W / 2, cy + 10, { align: "center" });

  doc.setFontSize(10);
  doc.text(`${config.dateFrom} – ${config.dateTo}`, PAGE_W / 2, cy + 20, { align: "center" });

  doc.setDrawColor(...PRIMARY);
  doc.setLineWidth(0.5);
  doc.line(MARGIN + 20, cy + 26, PAGE_W - MARGIN - 20, cy + 26);

  let ty = cy + 36;
  if (config.therapistName) {
    doc.setFontSize(10);
    doc.setTextColor(30, 30, 30);
    doc.text(`Prepared for: ${config.therapistName}`, PAGE_W / 2, ty, { align: "center" });
    ty += 7;
  }
  if (config.sessionDate) {
    doc.text(`Session date: ${config.sessionDate}`, PAGE_W / 2, ty, { align: "center" });
    ty += 7;
  }

  if (config.coverNote) {
    ty += 6;
    doc.setFontSize(9);
    doc.setTextColor(...MUTED);
    const noteLines = doc.splitTextToSize(config.coverNote, CONTENT_W - 20);
    doc.setFillColor(...LIGHT_BG);
    const boxH = noteLines.length * 5 + 10;
    doc.roundedRect(MARGIN + 10, ty - 5, CONTENT_W - 20, boxH, 2, 2, "F");
    doc.setTextColor(50, 50, 50);
    noteLines.forEach(line => { doc.text(line, PAGE_W / 2, ty, { align: "center" }); ty += 5; });
  }

  const fy = doc.internal.pageSize.height - 18;
  doc.setFontSize(8);
  doc.setTextColor(...MUTED);
  doc.text(`Generated by Oceans Symphony · ${format(new Date(), "MMMM d, yyyy")}`, PAGE_W / 2, fy, { align: "center" });
  if (config.confidentialityNotice) {
    doc.setFontSize(6.5);
    doc.text("Personal health information — shared voluntarily for therapeutic purposes.", PAGE_W / 2, fy + 5, { align: "center" });
  }
}

// ── OVERVIEW ──────────────────────────────────────────────────────────────────

function addOverview(doc, overview, y) {
  y = sectionHeader(doc, "At a Glance", y);
  doc.setFontSize(9);
  doc.setTextColor(50, 50, 50);

  const items = [
    [`${overview.frontingCount}`, "fronting sessions recorded"],
    [`${overview.checkInCount}`, "emotion check-ins"],
    [`${overview.journalCount}`, "journal entries"],
    [`${overview.diaryCardCount}`, "diary cards"],
    [`${overview.alterCount}`, "system members"],
  ];

  items.forEach(([n, label]) => {
    y = checkPageBreak(doc, y, 7);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...PRIMARY);
    doc.text(`${n}`, MARGIN + 3, y);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(50, 50, 50);
    doc.text(label, MARGIN + 3 + doc.getTextWidth(n) + 2, y);
    y += 6;
  });

  return y + 4;
}

// ── FRONTING HISTORY ──────────────────────────────────────────────────────────

function addFrontingSection(doc, frontingData, y) {
  y = checkPageBreak(doc, y, 30);
  y = sectionHeader(doc, "Fronting History", y);

  if (frontingData.summaryTable.length > 0) {
    y = drawTable(doc, ["System Member", "Total Time", "Sessions", "Primary"], 
      frontingData.summaryTable.map(r => [r.name, r.total, r.sessions, r.primary]), y,
      [CONTENT_W * 0.4, CONTENT_W * 0.2, CONTENT_W * 0.2, CONTENT_W * 0.2]);
    y += 6;
  }

  if (frontingData.noteworthy.length > 0) {
    y = checkPageBreak(doc, y, 14);
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(30, 30, 30);
    doc.text("Notable events", MARGIN, y);
    doc.setFont("helvetica", "normal");
    y += 5;
    frontingData.noteworthy.forEach(ev => {
      y = checkPageBreak(doc, y, 8);
      doc.setFontSize(8);
      doc.setTextColor(...MUTED);
      doc.text(ev.date || "", MARGIN + 2, y);
      flagBadge(doc, ev.label, MARGIN + 50, y);
      if (ev.detail) { doc.setTextColor(80, 80, 80); doc.text(ev.detail, MARGIN + 2, y + 5); y += 5; }
      y += 6;
    });
  }

  return y + 4;
}

// ── EMOTION CHECK-INS ─────────────────────────────────────────────────────────

function addEmotionSection(doc, emotionData, y) {
  y = checkPageBreak(doc, y, 30);
  y = sectionHeader(doc, "Emotion Check-Ins", y);

  if (emotionData.topEmotions.length > 0) {
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(30, 30, 30);
    doc.text("Most frequent emotions:", MARGIN, y);
    doc.setFont("helvetica", "normal");
    y += 5;
    emotionData.topEmotions.slice(0, 6).forEach(e => {
      y = checkPageBreak(doc, y, 6);
      doc.setFontSize(8);
      doc.setTextColor(50, 50, 50);
      doc.text(`• ${e.emotion} (${e.count}×)`, MARGIN + 3, y);
      y += 5;
    });
    y += 3;
  }

  if (emotionData.noteworthy.length > 0) {
    y = checkPageBreak(doc, y, 12);
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(30, 30, 30);
    doc.text("Notable check-ins:", MARGIN, y);
    doc.setFont("helvetica", "normal");
    y += 5;
    emotionData.noteworthy.forEach(ev => {
      y = checkPageBreak(doc, y, 12);
      doc.setFontSize(8);
      doc.setTextColor(...MUTED);
      doc.text(ev.date, MARGIN + 2, y);
      flagBadge(doc, ev.label, MARGIN + 55, y);
      y += 5;
      doc.setTextColor(60, 60, 60);
      if (ev.emotions) doc.text(`Emotions: ${ev.emotions}`, MARGIN + 4, y);
      y += 5;
    });
  }

  return y + 4;
}

// ── SYMPTOMS ──────────────────────────────────────────────────────────────────

function addSymptomsSection(doc, symptomsData, y) {
  y = checkPageBreak(doc, y, 30);
  y = sectionHeader(doc, "Symptoms & Habits", y);

  if (symptomsData.summaryTable.length > 0) {
    y = drawTable(doc, ["Symptom / Habit", "Check-ins", "Avg Score", "Sessions", "Total Duration"],
      symptomsData.summaryTable.map(r => [r.label + (r.isPositive ? " (+)" : ""), r.count, r.avgScore, r.activeSessions, r.totalDuration]), y,
      [CONTENT_W * 0.3, CONTENT_W * 0.15, CONTENT_W * 0.15, CONTENT_W * 0.15, CONTENT_W * 0.25]);
    y += 6;
  }

  if (symptomsData.noteworthy.length > 0) {
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(30, 30, 30);
    doc.text("Notable symptom events:", MARGIN, y);
    doc.setFont("helvetica", "normal");
    y += 5;
    symptomsData.noteworthy.forEach(ev => {
      y = checkPageBreak(doc, y, 8);
      doc.setFontSize(8);
      doc.setTextColor(...MUTED);
      doc.text(ev.date, MARGIN + 2, y);
      doc.setTextColor(60, 60, 60);
      doc.text(ev.label, MARGIN + 55, y);
      flagBadge(doc, ev.flag, MARGIN + 90, y);
      y += 6;
    });
  }

  return y + 4;
}

// ── ACTIVITIES ────────────────────────────────────────────────────────────────

function addActivitiesSection(doc, activitiesData, y) {
  y = checkPageBreak(doc, y, 20);
  y = sectionHeader(doc, "Activities", y);
  if (activitiesData.list.length === 0) {
    doc.setFontSize(8); doc.setTextColor(...MUTED);
    doc.text("No activities recorded in this period.", MARGIN, y); return y + 10;
  }
  y = drawTable(doc, ["Activity", "Times logged", "Total duration"],
    activitiesData.list.slice(0, 15).map(r => [r.name, r.count, r.duration]), y,
    [CONTENT_W * 0.5, CONTENT_W * 0.25, CONTENT_W * 0.25]);
  return y + 8;
}

// ── JOURNALS ──────────────────────────────────────────────────────────────────

function addJournalsSection(doc, journalData, journalDetail, y) {
  y = checkPageBreak(doc, y, 20);
  y = sectionHeader(doc, "Journal Entries", y);
  if (journalData.length === 0) {
    doc.setFontSize(8); doc.setTextColor(...MUTED);
    doc.text("No journal entries in this period.", MARGIN, y); return y + 10;
  }
  journalData.forEach(j => {
    y = checkPageBreak(doc, y, 14);
    doc.setFontSize(9);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(30, 30, 30);
    doc.text(j.title || "Untitled", MARGIN + 2, y);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(...MUTED);
    doc.text(j.date || "", PAGE_W - MARGIN, y, { align: "right" });
    y += 5;
    if (journalDetail !== "summaries" && (j.excerpt || j.content)) {
      const text = (j.content || j.excerpt || "").slice(0, journalDetail === "excerpts" ? 400 : undefined);
      doc.setTextColor(60, 60, 60);
      doc.setFontSize(8);
      y = wrappedText(doc, text + (journalDetail === "excerpts" && text.length >= 400 ? "…" : ""), MARGIN + 3, y, CONTENT_W - 6, 4.5);
      if (journalDetail === "excerpts") {
        doc.setTextColor(...MUTED);
        doc.setFontSize(7);
        doc.text("Full entry available in app.", MARGIN + 3, y); y += 4;
      }
    }
    y += 5;
  });
  return y + 2;
}

// ── DIARY CARDS ───────────────────────────────────────────────────────────────

function addDiarySection(doc, diaryData, y) {
  y = checkPageBreak(doc, y, 20);
  y = sectionHeader(doc, "Diary Card Log", y);
  if (diaryData.length === 0) {
    doc.setFontSize(8); doc.setTextColor(...MUTED);
    doc.text("No diary cards in this period.", MARGIN, y); return y + 10;
  }
  y = drawTable(doc, ["Date", "Emotions", "Urges", "Body/Mind", "Flags"],
    diaryData.map(d => [d.date, d.emotions?.slice(0, 20) || "—", d.urges?.slice(0, 20) || "—", d.bodyMind?.slice(0, 20) || "—", d.flags.join(", ") || "—"]), y,
    [CONTENT_W * 0.15, CONTENT_W * 0.2, CONTENT_W * 0.2, CONTENT_W * 0.25, CONTENT_W * 0.2]);
  return y + 8;
}

// ── CUSTOM STATUS NOTES ───────────────────────────────────────────────────────

function addStatusNotesSection(doc, statusNotes, y) {
  if (!statusNotes || statusNotes.length === 0) return y;
  y = checkPageBreak(doc, y, 30);
  y = sectionHeader(doc, "Custom Status Notes", y);
  statusNotes.forEach(entry => {
    y = checkPageBreak(doc, y, 12);
    doc.setFontSize(8);
    doc.setTextColor(...MUTED);
    doc.text(entry.date, MARGIN + 2, y);
    y += 5;
    doc.setTextColor(50, 50, 50);
    y = wrappedText(doc, entry.note, MARGIN + 4, y, CONTENT_W - 8, 4.5);
    if (entry.emotions) {
      doc.setTextColor(...MUTED);
      doc.setFontSize(7.5);
      doc.text(`Emotions: ${entry.emotions}`, MARGIN + 4, y);
      y += 4.5;
    }
    y += 4;
  });
  return y + 4;
}

// ── PATTERNS SUMMARY ──────────────────────────────────────────────────────────

function addPatternsSection(doc, patternsData, y) {
  y = checkPageBreak(doc, y, 30);
  y = sectionHeader(doc, "Patterns & Narrative", y);

  // Handle both legacy string format and new { paragraphs, earlyWarning } object
  const paragraphs = typeof patternsData === "string"
    ? [patternsData]
    : (patternsData?.paragraphs || []);
  const earlyWarning = typeof patternsData === "string" ? null : patternsData?.earlyWarning;

  // Early warning banner
  if (earlyWarning?.status === "warning" || earlyWarning?.status === "elevated") {
    const isWarning = earlyWarning.status === "warning";
    y = checkPageBreak(doc, y, 20);
    const msgLines = earlyWarning.message
      ? doc.splitTextToSize(earlyWarning.message, CONTENT_W - 8)
      : [];
    const bannerH = 10 + msgLines.length * 4.5;
    doc.setFillColor(...(isWarning ? [254, 226, 226] : [255, 237, 213]));
    doc.setDrawColor(...(isWarning ? [239, 68, 68] : [249, 115, 22]));
    doc.setLineWidth(0.4);
    doc.roundedRect(MARGIN, y, CONTENT_W, bannerH, 2, 2, "FD");
    doc.setFontSize(8);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...(isWarning ? [185, 28, 28] : [194, 65, 12]));
    doc.text(isWarning ? "Pattern alert" : "Elevated pattern", MARGIN + 3, y + 6);
    if (msgLines.length > 0) {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(7.5);
      doc.setTextColor(50, 50, 50);
      msgLines.forEach((line, i) => {
        doc.text(line, MARGIN + 3, y + 11 + i * 4.5);
      });
    }
    y += bannerH + 4;
  }

  // Narrative paragraphs
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(50, 50, 50);
  paragraphs.forEach(p => {
    y = checkPageBreak(doc, y, 12);
    y = wrappedText(doc, p, MARGIN + 2, y, CONTENT_W - 4, 5.5);
    y += 3;
  });

  return y + 5;
}

// ── ALTER APPENDIX ────────────────────────────────────────────────────────────

function addAlterAppendix(doc, appendix, y) {
  if (appendix.length === 0) return y;
  doc.addPage();
  y = 18;
  y = sectionHeader(doc, "Appendix: System Members", y);
  appendix.forEach(a => {
    y = checkPageBreak(doc, y, 18);
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(30, 30, 30);
    doc.text(a.name, MARGIN + 2, y);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(...MUTED);
    const meta = [a.pronouns, a.role].filter(Boolean).join(" · ");
    if (meta) { doc.text(meta, MARGIN + 2, y + 5); y += 5; }
    y += 5;
    if (a.bio) {
      doc.setTextColor(60, 60, 60);
      y = wrappedText(doc, a.bio, MARGIN + 4, y, CONTENT_W - 8, 4.5);
    }
    y += 6;
  });
  return y;
}

function addSimpleListSection(doc, title, lines, y) {
  if (!lines || lines.length === 0) return y;
  y = checkPageBreak(doc, y, 20);
  y = sectionHeader(doc, title, y);
  lines.forEach(line => {
    const parts = line.split("\n");
    parts.forEach((part, i) => {
      y = checkPageBreak(doc, y, 6);
      doc.setFontSize(i === 0 ? 8.5 : 8);
      doc.setFont("helvetica", i === 0 ? "normal" : "normal");
      doc.setTextColor(...(i === 0 ? [30, 30, 30] : MUTED));
      y = wrappedText(doc, part, MARGIN + (i > 0 ? 6 : 2), y, CONTENT_W - (i > 0 ? 6 : 2), 4.5);
    });
    y += 2;
  });
  return y + 4;
}

// ── PLAIN TEXT EXPORT ─────────────────────────────────────────────────────────

function formatAsPlainText({
  config,
  sections,
  enabledSections,
}) {
  let text = "";

  // Header
  text += `${"=".repeat(60)}\n`;
  text += `THERAPY REPORT\n`;
  text += `${config.systemName || "My System"} | ${config.dateFrom} to ${config.dateTo}\n`;
  text += `${"=".repeat(60)}\n\n`;

  if (config.therapistName) {
    text += `Prepared for: ${config.therapistName}\n`;
  }
  if (config.sessionDate) {
    text += `Session date: ${config.sessionDate}\n`;
  }
  if (config.coverNote) {
    text += `\nNote: ${config.coverNote}\n`;
  }
  if (config.therapistName || config.sessionDate || config.coverNote) {
    text += `\nGenerated: ${format(new Date(), "MMMM d, yyyy")}\n`;
    text += "\n";
  }

  // Overview
  if (enabledSections.has("overview")) {
    text += `OVERVIEW\n${"--------".padEnd(60, "-")}\n`;
    const o = sections.overview;
    text += `${o.frontingCount} fronting sessions recorded\n`;
    text += `${o.checkInCount} emotion check-ins\n`;
    text += `${o.journalCount} journal entries\n`;
    text += `${o.diaryCardCount} diary cards\n`;
    text += `${o.alterCount} system members\n\n`;
  }

  // Fronting History
  if (enabledSections.has("fronting") && sections.fronting) {
    text += `FRONTING HISTORY\n${"--------".padEnd(60, "-")}\n`;
    if (sections.fronting.summaryTable.length > 0) {
      text += `\nSummary by member:\n`;
      sections.fronting.summaryTable.forEach(r => {
        text += `  • ${r.name}: ${r.total} total time, ${r.sessions} sessions, primary: ${r.primary}\n`;
      });
    }
    if (sections.fronting.noteworthy.length > 0) {
      text += `\nNotable events:\n`;
      sections.fronting.noteworthy.forEach(ev => {
        text += `  • ${ev.date || ""}${ev.label ? ` [${ev.label}]` : ""}${ev.detail ? ` — ${ev.detail}` : ""}\n`;
      });
    }
    text += "\n";
  }

  // Emotion Check-Ins
  if (enabledSections.has("emotions") && sections.emotions) {
    text += `EMOTION CHECK-INS\n${"--------".padEnd(60, "-")}\n`;
    if (sections.emotions.topEmotions.length > 0) {
      text += `\nMost frequent emotions:\n`;
      sections.emotions.topEmotions.slice(0, 6).forEach(e => {
        text += `  • ${e.emotion} (${e.count}×)\n`;
      });
    }
    if (sections.emotions.noteworthy.length > 0) {
      text += `\nNotable check-ins:\n`;
      sections.emotions.noteworthy.forEach(ev => {
        text += `  • ${ev.date}${ev.label ? ` [${ev.label}]` : ""}\n`;
        if (ev.emotions) text += `    Emotions: ${ev.emotions}\n`;
      });
    }
    text += "\n";
  }

  // Custom Status Notes
  if (sections.statusNotes?.length > 0) {
    text += `CUSTOM STATUS NOTES\n${"--------".padEnd(60, "-")}\n`;
    sections.statusNotes.forEach(entry => {
      text += `\n  ${entry.date}\n`;
      text += `  💬 ${entry.note}\n`;
      if (entry.emotions) text += `    Emotions: ${entry.emotions}\n`;
    });
    text += "\n";
  }

  // Symptoms
  if (enabledSections.has("symptoms") && sections.symptoms) {
    text += `SYMPTOMS & HABITS\n${"--------".padEnd(60, "-")}\n`;
    if (sections.symptoms.summaryTable.length > 0) {
      text += `\nSummary:\n`;
      sections.symptoms.summaryTable.forEach(r => {
        const scoreLabel = r.isPositive ? "avg score (higher=better)" : "avg severity";
        text += `  • ${r.label}${r.isPositive ? " [positive]" : ""}: ${r.count} check-ins, ${scoreLabel} ${r.avgScore}, ${r.activeSessions} sessions\n`;
      });
    }
    if (sections.symptoms.noteworthy.length > 0) {
      text += `\nNotable events:\n`;
      sections.symptoms.noteworthy.forEach(ev => {
        text += `  • ${ev.date}: ${ev.label}${ev.flag ? ` [${ev.flag}]` : ""}\n`;
      });
    }
    text += "\n";
  }

  // Activities
  if (enabledSections.has("activities") && sections.activities) {
    text += `ACTIVITIES\n${"--------".padEnd(60, "-")}\n`;
    if (sections.activities.list.length > 0) {
      sections.activities.list.slice(0, 15).forEach(a => {
        text += `  • ${a.name}: ${a.count} times, ${a.duration} total\n`;
      });
    } else {
      text += "No activities recorded in this period.\n";
    }
    text += "\n";
  }

  // Journals
  if (enabledSections.has("journals") && sections.journals) {
    text += `JOURNAL ENTRIES\n${"--------".padEnd(60, "-")}\n`;
    if (sections.journals.length > 0) {
      sections.journals.forEach(j => {
        text += `\n  "${j.title || "Untitled"}" (${j.date})\n`;
        if (j.content) {
          text += `  ${j.content}\n`;
        } else if (j.excerpt) {
          text += `  ${j.excerpt}${j.excerpt.length >= 400 ? "…" : ""}\n`;
        }
      });
    } else {
      text += "No journal entries in this period.\n";
    }
    text += "\n";
  }

  // Diary Cards
  if (enabledSections.has("diary") && sections.diary) {
    text += `DIARY CARD LOG\n${"--------".padEnd(60, "-")}\n`;
    if (sections.diary.length > 0) {
      sections.diary.forEach(d => {
        text += `\n  ${d.date}:\n`;
        if (d.emotions) text += `    Emotions: ${d.emotions}\n`;
        if (d.urges) text += `    Urges: ${d.urges}\n`;
        if (d.bodyMind) text += `    Body/Mind: ${d.bodyMind}\n`;
        if (d.flags?.length > 0) text += `    Flags: ${d.flags.join(", ")}\n`;
      });
    } else {
      text += "No diary cards in this period.\n";
    }
    text += "\n";
  }

  // Bulletins
  if (enabledSections.has("bulletins") && sections.bulletins?.length > 0) {
    text += `BULLETIN BOARD\n${"--------".padEnd(60, "-")}\n`;
    sections.bulletins.forEach(b => {
      text += `\n  [${b.date}]${b.isPinned ? " 📌" : ""} ${b.title}`;
      if (b.author) text += ` — by ${b.author}`;
      text += "\n";
      if (b.content) text += `  ${b.content.slice(0, 300)}${b.content.length > 300 ? "..." : ""}\n`;
    });
    text += "\n";
  }

  // System Check-Ins
  if (enabledSections.has("systemCheckIns") && sections.systemCheckIns?.length > 0) {
    text += `SYSTEM CHECK-INS\n${"--------".padEnd(60, "-")}\n`;
    sections.systemCheckIns.forEach(c => {
      text += `\n  [${c.date}] ${c.title}`;
      if (c.overallRating != null) text += ` — Rating: ${c.overallRating}`;
      text += "\n";
      if (c.summary) text += `  ${c.summary}\n`;
    });
    text += "\n";
  }

  // Tasks
  if (enabledSections.has("tasks") && sections.tasks?.frequencySummary?.length > 0) {
    text += `TASKS & HABITS\n${"--------".padEnd(60, "-")}\n`;
    sections.tasks.frequencySummary.forEach(f => {
      text += `  ${f.frequency}: ${f.periods} period(s) tracked, avg ${f.avgCompleted} tasks completed\n`;
    });
    text += "\n";
  }

  // Patterns
  if (enabledSections.has("patterns") && sections.patterns) {
    text += `PATTERNS & NARRATIVE\n${"--------".padEnd(60, "-")}\n`;
    if (typeof sections.patterns === "string") {
      text += `${sections.patterns}\n\n`;
    } else {
      const { paragraphs = [], earlyWarning } = sections.patterns;
      if (earlyWarning?.status === "warning" || earlyWarning?.status === "elevated") {
        text += `⚠ ${earlyWarning.status === "warning" ? "PATTERN ALERT" : "ELEVATED PATTERN"}\n`;
        if (earlyWarning.message) text += `${earlyWarning.message}\n`;
        text += "\n";
      }
      paragraphs.forEach(p => { text += `${p}\n\n`; });
    }
  }

  // Alter Appendix
  if (enabledSections.has("alterAppendix") && sections.alterAppendix?.length > 0) {
    text += `APPENDIX: SYSTEM MEMBERS\n${"--------".padEnd(60, "-")}\n`;
    sections.alterAppendix.forEach(a => {
      text += `\n  ${a.name}`;
      if (a.pronouns || a.role) {
        text += ` (${[a.pronouns, a.role].filter(Boolean).join(" · ")})`;
      }
      text += "\n";
      if (a.bio) {
        text += `  ${a.bio}\n`;
      }
    });
    text += "\n";
  }

  text += `${"=".repeat(60)}\n`;
  text += `Personal health information — shared voluntarily for therapeutic purposes.\n`;

  return text;
}

// ── MAIN EXPORT ───────────────────────────────────────────────────────────────

export async function generateTherapyReport({
  config,
  sections,
  enabledSections,
}) {
  const doc = new jsPDF({ unit: "mm", format: "a4" });

  if (config.showCoverPage) {
    addCoverPage(doc, config);
    doc.addPage();
  }

  let y = 18;

  if (enabledSections.has("overview")) {
    y = addOverview(doc, sections.overview, y);
  }
  if (enabledSections.has("fronting") && sections.fronting) {
    y = addFrontingSection(doc, sections.fronting, y);
  }
  if (enabledSections.has("emotions") && sections.emotions) {
    y = addEmotionSection(doc, sections.emotions, y);
  }
  if (sections.statusNotes?.length > 0) {
    y = addStatusNotesSection(doc, sections.statusNotes, y);
  }
  if (enabledSections.has("symptoms") && sections.symptoms) {
    y = addSymptomsSection(doc, sections.symptoms, y);
  }
  if (enabledSections.has("activities") && sections.activities) {
    y = addActivitiesSection(doc, sections.activities, y);
  }
  if (enabledSections.has("journals") && sections.journals) {
    y = addJournalsSection(doc, sections.journals, config.journalDetail || "summaries", y);
  }
  if (enabledSections.has("diary") && sections.diary) {
    y = addDiarySection(doc, sections.diary, y);
  }
  if (enabledSections.has("bulletins") && sections.bulletins?.length > 0) {
    y = addSimpleListSection(doc, "Bulletin Board", sections.bulletins.map(b =>
      `[${b.date}]${b.isPinned ? " 📌" : ""} ${b.title}${b.author ? " — " + b.author : ""}${b.content ? "\n  " + b.content.slice(0, 200) : ""}`
    ), y);
  }
  if (enabledSections.has("systemCheckIns") && sections.systemCheckIns?.length > 0) {
    y = addSimpleListSection(doc, "System Check-Ins", sections.systemCheckIns.map(c =>
      `[${c.date}] ${c.title}${c.overallRating != null ? " — Rating: " + c.overallRating : ""}${c.summary ? "\n  " + c.summary : ""}`
    ), y);
  }
  if (enabledSections.has("tasks") && sections.tasks?.frequencySummary?.length > 0) {
    y = addSimpleListSection(doc, "Tasks & Habits", sections.tasks.frequencySummary.map(f =>
      `${f.frequency}: ${f.periods} period(s), avg ${f.avgCompleted} completed`
    ), y);
  }
  if (enabledSections.has("patterns") && sections.patterns) {
    y = addPatternsSection(doc, sections.patterns, y);
  }
  if (enabledSections.has("alterAppendix") && sections.alterAppendix?.length > 0) {
    addAlterAppendix(doc, sections.alterAppendix, y);
  }

  const total = doc.internal.getNumberOfPages();
  for (let i = 1; i <= total; i++) {
    doc.setPage(i);
    pageFooter(doc, config, i);
  }

  const slug = (config.systemName || "system").toLowerCase().replace(/\s+/g, "-").replace(/[^a-z0-9-]/g, "");
  const filename = `${slug}-therapy-report-${config.dateFrom}-to-${config.dateTo}.pdf`;
  const blob = doc.output("blob");
  return { blob, filename };
}

export function formatTherapyReportAsText({
  config,
  sections,
  enabledSections,
}) {
  return formatAsPlainText({ config, sections, enabledSections });
}